import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import UserLayout from '../../component/layout/UserLayout'
import MainBreadCrumb from '../../component/breadcrumb/MainBreadCrumb'

const ReturnsAndRefunds = () => {
  return (
    <UserLayout>
      <MainBreadCrumb title="Returns And Refunds" />
      <section>
        <Container>
          <Row>
            <Col md="12">
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam suscipit accusantium ab blanditiis amet eaque architecto laudantium vero ducimus saepe, omnis, minus ipsa porro odit repellat aperiam voluptatibus alias atque aliquam, sit dolor necessitatibus! Expedita laborum libero molestias quasi excepturi laudantium consectetur incidunt sint laboriosam est voluptates, dolore, maiores labore autem cupiditate, quia perspiciatis nostrum. Corrupti debitis tempore recusandae distinctio dignissimos delectus obcaecati, dolores sint, veritatis sunt eos nisi eaque fugiat quae. Laborum optio itaque pariatur temporibus. Ab velit, doloribus rerum tempore rem inventore odio. Enim tempora consectetur accusamus cumque. Officiis quae dignissimos, magnam dolores iusto recusandae aperiam cumque quaerat quod ipsum ducimus, pariatur provident magni ipsam, quas officia numquam molestiae voluptatem. Placeat accusamus amet laborum vitae tempora, eum blanditiis qui ex exercitationem voluptatum quo corrupti ut, excepturi aliquid unde beatae dolorem quae suscipit optio odit ipsum reiciendis! Ullam qui non veniam pariatur beatae? Maiores expedita qui exercitationem debitis harum.</p>
              <p>Quos consectetur modi, nobis magni, aliquid laudantium quae harum ipsa quidem culpa quo veritatis aut illum nihil quas totam eum nisi in molestiae veniam debitis voluptate sapiente tempore optio. Amet, minima! Assumenda magnam culpa dolorem modi quia quam ad voluptates animi, sed voluptatem vel debitis at. Voluptatum est, nulla ipsam ratione eveniet animi ex voluptates accusamus sit, suscipit dolorem nihil nemo ea! Optio aspernatur modi voluptas cupiditate maiores provident. Dolorum quaerat illo corrupti, odit earum, vel sapiente quod nemo vero eveniet, dolore fugit sit natus nobis itaque ipsum nam quia. Vero, id perferendis. Eligendi vitae sed voluptate velit a! Mollitia deleniti nesciunt ducimus veniam ipsum, officiis quae eum necessitatibus assumenda adipisci culpa neque laborum quam esse, ut dolor sapiente velit quia, ea ab nisi laboriosam. Recusandae facilis modi a nemo corrupti id est quis, quidem voluptatum? Molestiae sint autem debitis est accusamus? Eligendi id consequatur maiores libero qui debitis vitae.</p>
              <p>Iusto voluptatibus eaque mollitia facere est ipsam sed illum, vitae quo, esse porro maiores culpa dolorem quia reprehenderit unde et assumenda ut natus! Corporis cum incidunt, maxime enim sed vel obcaecati eaque voluptatem architecto atque dolorum eveniet eos veritatis quaerat rerum autem nulla non soluta! Nesciunt amet perspiciatis ipsa natus labore quod omnis inventore error animi repellat sed ex harum earum, corrupti expedita deserunt quibusdam facilis quis? Recusandae error ratione, blanditiis ad, explicabo distinctio corrupti ut voluptatibus amet, sapiente temporibus alias obcaecati eveniet commodi nihil voluptate quas? Et voluptate illum adipisci. Laborum laboriosam explicabo, voluptatibus distinctio quibusdam reiciendis sed accusamus necessitatibus ipsam, eum tenetur soluta porro architecto mollitia. Cum minima temporibus ipsum at ducimus natus quisquam debitis, obcaecati itaque alias culpa qui! Officia, commodi alias ut sint aut explicabo iusto ipsa esse labore ducimus quaerat dolores minus pariatur officiis asperiores illum magni ipsum itaque nihil. Architecto maxime iure voluptate tempora.</p>
              <p>Accusantium commodi sapiente in cum enim dolorum, accusamus odit possimus delectus vitae labore natus deserunt illum libero. Nisi porro inventore sed dignissimos facilis atque et quidem perferendis omnis asperiores error architecto, pariatur voluptatibus quibusdam ipsa enim dolorem deleniti! Recusandae ipsa praesentium animi officiis eum iste eligendi nulla doloribus possimus magni. Amet, porro praesentium reprehenderit repellat obcaecati mollitia quas ipsum quisquam inventore magnam molestias iure necessitatibus nam soluta quia in cumque rerum, ex maiores quis dolor! Molestias accusantium dolor optio explicabo animi dicta, velit corrupti a adipisci vel. Cupiditate dolor vero tempora non eos cumque consectetur? Error ex quam velit dolorem ab totam quo praesentium deleniti eum impedit magnam nostrum minus at ducimus dolorum, quos eaque, doloremque suscipit nobis harum nihil expedita? Aut nobis saepe ducimus ratione ex in sapiente, laboriosam ut officia modi voluptates animi magnam ab quis cupiditate tempore consequatur fugit, architecto iure vitae quas! Quis vero ipsam veritatis.</p>
              <p>Adipisci labore quod facilis saepe dolore odio autem doloremque perferendis dolor eveniet neque, incidunt nisi, maxime tenetur iste, magni inventore deleniti maiores pariatur obcaecati eius! Distinctio, mollitia dolore voluptates vel, ducimus accusantium vitae sint nostrum fugiat doloribus placeat veniam harum cupiditate porro minima excepturi ea provident quod earum amet. Cupiditate, atque ipsam tenetur ab iste in quisquam iusto enim harum esse quos delectus nihil porro? Repellat nobis reiciendis aut, excepturi temporibus ab ullam hic sequi minus autem ipsum? Neque expedita quo eligendi numquam fugit possimus eum dicta a ducimus vero, quibusdam officiis fuga impedit pariatur qui delectus consequatur assumenda ratione magnam nisi deserunt odio sequi. Vel corporis eaque tempora vitae ad fugit? Sapiente distinctio cupiditate debitis magnam, tenetur non veritatis, maxime illo repellat labore, alias ratione animi tempora ea suscipit quos perferendis dolores! Eos voluptate porro vel quisquam. Molestias reprehenderit cumque molestiae quod, doloremque laboriosam ipsum voluptatem laudantium exercitationem aspernatur?</p>
              <p>Obcaecati molestias temporibus odio nostrum reprehenderit perspiciatis, quidem minus, nobis at, quibusdam vel possimus. Animi ipsum atque iste a, vero dignissimos voluptate repudiandae voluptatem porro inventore nostrum nobis maxime, perferendis laborum doloremque repellendus quasi commodi vel neque! Autem, perspiciatis. Nesciunt eum quia a enim? Quibusdam obcaecati sed saepe libero, aliquam, dolore tempora id impedit, perferendis eligendi adipisci consectetur harum beatae molestiae asperiores culpa dignissimos laborum quam quia? Autem dolorem modi odio, ad voluptate dicta corrupti omnis ratione quos et enim odit architecto unde perferendis! Quo, dignissimos. Hic, non? Sunt dolor tenetur veniam facere nostrum necessitatibus nihil debitis tempora optio, ipsum repellendus, hic cumque laudantium quod eveniet itaque maxime temporibus ducimus praesentium voluptate alias consequuntur doloribus excepturi est. Exercitationem id perspiciatis libero pariatur esse nisi, voluptatum autem veritatis molestiae laborum neque quasi excepturi totam beatae, et nemo amet quam. Totam eum cupiditate laborum illum, reiciendis temporibus deserunt vero. Deserunt, voluptates repudiandae?</p>
            </Col>
          </Row>
        </Container>
      </section>
    </UserLayout>
  )
}

export default ReturnsAndRefunds